### PR TITLE
Raise on invalid function name

### PR DESCRIPTION
**Pull request by michalhabera**

### CODE REVIEW

**Comment by garth-wells** [comment]
@michalhabera any chance of some tests?

**Comment by garth-wells** [comment]
@michalhabera ping again, could you add a test?

**Comment by michalhabera** [comment]
> @michalhabera ping again, could you add a test?

What should the test do? The PR adds better explaining RuntimeError for invalid naming. It does not change
when the code fails, only how it fails.

**Comment by jhale** [comment]
You can get pytest to test that an exception is raised or not? I can't think of anything else.

**Comment by garth-wells** [comment]
@michalhabera check that exception is raised for an invalid name.

**Comment by michalhabera** [comment]
Exceptions were caught and re-thrown in `jit.py`, so in order to preserve its type needs another try block. Moreover, Coefficients have user-given names only in dolfinx, so test at the FFCx level requires monkey patching, see the test.
Now you see why "testing" this is not very neat.

**Review by garth-wells — APPROVED** [review]

**Pull request merged**
