### PR TITLE
Update version number

### PR DESCRIPTION
**Pull request by mscroggs**
@chrisrichardson Does this one need updating too?

Seems to be causing failures like this: https://github.com/FEniCS/dolfinx/runs/6193714382?check_suite_focus=true

### CODE REVIEW

**Comment by ma595** [comment]
Yes, this change will also enable the fenics-dolfinx spack package to build with fenics-ufcx.

**Comment by chrisrichardson** [comment]
Yes, I agree. There are version numbers in too many places.
Maybe we will need to make a 0.4.1 release of ffcx? Or I can just retag? Any thoughts @ma595?

**Review by chrisrichardson — APPROVED** [review]

**Comment by ma595** [comment]
I slightly prefer retagging 0.4.0.

**Comment by mscroggs** [comment]
I agree. Having a version 0.4.0 that's out there but broken seems a bad idea

**Pull request merged**
