### PR TITLE
Set pygraphviz version to 1.7

### LINKED ISSUE #449: `PyGraphviz requires Python version 3.8 or later (3.7 detected).`
I'm getting this error when running CI (https://github.com/FEniCS/ffcx/runs/5035402568?check_suite_focus=true). Do we need to bump our minimum Python requirement to 3.8?

### PR DESCRIPTION
**Pull request by mscroggs**
Fixes #449

### CODE REVIEW

**Comment by garth-wells** [comment]
I don't think this is a sustainable fix. I'd be happier to drop Python 3.7 from the CI, and have 3.8. 3.9 and 3.10.

**Comment by jorgensd** [comment]
> I don't think this is a sustainable fix. I'd be happier to drop Python 3.7 from the CI, and have 3.8. 3.9 and 3.10.

I think it is quite strict to drop Python 3.7 before it reaches end of life (June 2023).

**Comment by garth-wells** [comment]
> > I don't think this is a sustainable fix. I'd be happier to drop Python 3.7 from the CI, and have 3.8. 3.9 and 3.10.
> 
> I think it is quite strict to drop Python 3.7 before it reaches end of life (June 2023).

We're not dropping Python 3.7. It's about the CI. FFCx has a tiny dependency on `pygraphviz` - the functionality it provides is peripheral. A point is that we have always strived to work with the the latest releases of libraries. Deviating form this leads to major dependency management challenges.

**Comment by jhale** [comment]
Greater than or equal to is more flexible for dependencies.

**Comment by jhale** [comment]
Sorry I misread the issue.

I am going to close this this. I agree with @garth-wells, we should drop 3.7 from the CI. We don't have the resources to deal with being compatible with legacy packages.

**Pull request closed without merging**
